apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-sample
    app.kubernetes.io/part-of: raleighnc
  name: java-springboot-sample
  namespace: rhn-support-tshearon
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: java-springboot-sample
    weight: 100
status: {}
